# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gazette' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gazette
pod 'Alamofire', '~> 4.4'
pod 'ObjectMapper', '~> 2.2'
pod 'KeychainSwift', '~> 7.0'
pod 'RealmSwift', '~> 2.4'
pod 'XLActionController', '~> 3.0'
pod 'QRCode', '~> 2.0'
pod 'HTTPStatusCodes', '~> 3.1.1'
pod 'PKHUD', '~> 4.0'
end
